### ISSUE TITLE
Milestone 1 - Prep for hardcoding

### ISSUE THREAD

**Issue by Exouxas** [Exouxas/FosterScript.Core#2]
### All classes required for making the MVP for a hardcoded "AI":
- [ ] Agents.Actor.cs
- [ ] Agents.Module.cs
- [ ] Environments.World.cs
- [ ] Environments.IndefiniteWorld.cs

#### Actor.cs
Takes functionality from the Module subclasses added to its module "reservior". Needs to be able to function in a World.

#### Module.cs
The logic for when an Actor needs to sense something or act on something in a World.

#### World.cs
The basis for both IndefiniteWorld.cs and FiniteWorld.cs. Needs more description I think.

#### IndefiniteWorld.cs
An instance of this contains several Actors (which can be Learners in the future, as Actor is the superclass of Learner), and allows for those Actors to interact with and perceive their surroundings. Will have an integrated clock cycle, run on a thread, and not have a definite time to stop. The FiniteWorld.cs class will be the altered version of this that runs X cycles.

### Functionalities needed:
- [ ] JSON (or other type of serialization) for save/load/reuse. This one seems complicated due to the interconnectedness of the classes, so it will be its own issue.
