### ISSUE TITLE
Milestone 2 - Everything needed for publishing the repo

### ISSUE THREAD

**Issue by Exouxas** [Exouxas/FosterScript.Core#3]
### All classes required for making the MVP for a functioning AI:
- [ ] NeuralNetwork.Brain.cs
- [ ] Agents.Learner.cs
- [ ] Environments.FiniteWorld.cs
- [ ] Dependency.cs

#### Brain.cs
Contains a list or lists of nodes, and calculates these. Nodes contain a "Calculate" and a "Propagate" method, these will be in Brain.cs too, and will start a propagation process and a calculation process. Both will be threaded, but the methods will be synchronized to make using them easier (calling Propagate() should act the same as if it wasn't threaded, but have the 

#### Learner.cs
An Actor.cs with a Brain.cs in it.

#### FiniteWorld.cs
An instance of this contains several Actors (which can be Learners in the future, as Actor is the superclass of Learner), and allows for those Actors to interact with and perceive their surroundings. Will run without an integrated clock cycle, and instead finish ASAP. If it's very similar to IndefiniteWorld.cs, then some functionality should either be moved over to World.cs or be implemented directly from IndefiniteWorld.cs through inheritance.

#### Dependency.cs
Allows an inheriting class to be dependent on in other classes. This is to make the dynamic loader possible without crashing if one file is missing.
